### ISSUE TITLE
CLI tools - oc sync fails on Windows 10

### ISSUE THREAD

**Issue by gasgithub** [ibm-garage-cloud/ibm-garage-developer-guide#221]
**Describe the bug**
oc sync command fails with the following error:

```
E:\demo-node-typescript>oc sync demo-node-typescript --dev
Setting up namespace demo-node-typescript and serviceAccount default
- Setting up namespace: demo-node-typescriptError preparing namespace Error: clusters[0].cluster.server is missing
    at C:\Users\userx\AppData\Roaming\npm\node_modules\@ibmgaragecloud\cloud-native-toolkit-cli\node_modules\@kubernetes\client-node\dist\config_types.js:18:19
    at Function.map (C:\Users\userx\AppData\Roaming\npm\node_modules\@ibmgaragecloud\cloud-native-toolkit-cli\node_modules\@kubernetes\client-node\node_modules\underscore\underscore.js:1249:24)
    at Object.newClusters (C:\Users\userx\AppData\Roaming\npm\node_modules\@ibmgaragecloud\cloud-native-toolkit-cli\node_modules\@kubernetes\client-node\dist\config_types.js:6:14)
    at KubeConfig.loadFromString (C:\Users\userx\AppData\Roaming\npm\node_modules\@ibmgaragecloud\cloud-native-toolkit-cli\node_modules\@kubernetes\client-node\dist\config.js:94:40)
    at KubeConfig.loadFromFile (C:\Users\userx\AppData\Roaming\npm\node_modules\@ibmgaragecloud\cloud-native-toolkit-cli\node_modules\@kubernetes\client-node\dist\config.js:65:14)
    at KubeConfig.loadFromDefault (C:\Users\userx\AppData\Roaming\npm\node_modules\@ibmgaragecloud\cloud-native-toolkit-cli\node_modules\@kubernetes\client-node\dist\config.js:201:22)
    at ServerUrl.<anonymous> (C:\Users\userx\AppData\Roaming\npm\node_modules\@ibmgaragecloud\cloud-native-toolkit-cli\dist\util\server-url.js:10:24)
    at Generator.next (<anonymous>)
    at C:\Users\userx\AppData\Roaming\npm\node_modules\@ibmgaragecloud\cloud-native-toolkit-cli\node_modules\tslib\tslib.js:114:75
    at new Promise (<anonymous>)
exit status 1
```

oc is correctly configured and returns for example:
```
oc get nodes
NAME          STATUS   ROLES           AGE   VERSION
10.75.7.147   Ready    master,worker   4d    v1.17.1+45f8ddb
10.75.7.183   Ready    master,worker   4d    v1.17.1+45f8ddb
```

Same with kubectl
```
kubectl get nodes
NAME          STATUS   ROLES           AGE   VERSION
10.75.7.147   Ready    master,worker   4d    v1.17.1+45f8ddb
10.75.7.183   Ready    master,worker   4d    v1.17.1+45f8ddb
```
**To Reproduce**
1. Install toolkit
2. Create sample project
3. Issue `oc sync myproject --dev`

**Expected behavior**
Command should be invoked correctly and copy configmaps and secrets

**Desktop (please complete the following information):**
 - OS: Win10

**Comment by gasgithub** [comment]
This was problem in local `.kube\config` file contained `cluster` entry with empty server like this: `server=''`
